{% set version = "1.1-3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-venneuler
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/venneuler_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/venneuler/venneuler_{{ version }}.tar.gz
  sha256: 21d3ac847350bdabf8e7b22e594683cd6f4172b724caa7c4be57dd1a082dd97e

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rjava
  run:
    - r-base
    - r-rjava

test:
  commands:
    - $R -e "library('venneuler')"           # [not win]
    - "\"%R%\" -e \"library('venneuler')\""  # [win]

about:
  home: http://www.rforge.net/venneuler/, http://www.cs.uic.edu/~wilkinson/
  license: MPL-1.1
  summary: Calculates and displays Venn and Euler Diagrams
  license_family: OTHER

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf

# Package: venneuler
# Version: 1.1-0
# Title: Venn and Euler Diagrams
# Author: Lee Wilkinson <leland.wilkinson@gmail.com>
# Maintainer: Simon Urbanek <simon.urbanek@r-project.org>
# Depends: rJava
# Description: Calculates and displays Venn and Euler Diagrams
# SystemRequirement: Java 1.5 or higher
# License: MPL-1.1
# URL: http://www.rforge.net/venneuler/, http://www.cs.uic.edu/~wilkinson/
# Repository: CRAN
# Date/Publication: 2011-08-10 05:50:44
